server:
  port: 12580

spring:
  profiles:
    active: prod
  application:
    name: fastdfs-client


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kd.fastdfsclient.entity

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.100.3.50:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: 192.100.3.50
#    instance-id: 192.100.3.50